# Production Docker Compose Configuration
services:
  server:
    build:
      context: .
    container_name: flowise_server_prod
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.prod
    networks:
      - flowise_network

  db:
    image: postgres:17
    container_name: flowise_db_prod
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - flowise_network

volumes:
  postgres_data_prod:

networks:
  flowise_network:
    driver: bridge

