# Development Docker Compose Configuration
services:
  server:
    build:
      context: .
    container_name: flowise_server_dev
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env.dev
    volumes:
      - .:/app
    networks:
      - flowise_network_dev

  db:
    image: postgres:17
    container_name: flowise_db_dev
    restart: unless-stopped
    env_file:
      - .env.dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - flowise_network_dev

  redis:
    image: redis:7-alpine
    container_name: flowise_redis_dev
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - flowise_network_dev

volumes:
  postgres_data_dev:

networks:
  flowise_network_dev:
    driver: bridge